version: '3.5'

services:
  zookeeper:
    container_name: zookeper
    image: zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - node-kafka

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERSITED_HOST_NAME}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper 
      KAFKA_CREATE_TOPICS: 'user:1:1,user-response:1:1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - node-kafka

networks:
  node-kafka:
    driver: bridge
    name: node_kafka